
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.diabolica.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.diabolica.block.TilesBlock;
import net.mcreator.diabolica.block.StripedLiminalRoadBlock;
import net.mcreator.diabolica.block.RoadPlacerBlock;
import net.mcreator.diabolica.block.RoadPlacer2Block;
import net.mcreator.diabolica.block.PlasterBlock;
import net.mcreator.diabolica.block.LiminalRoadBlock;
import net.mcreator.diabolica.block.LimboBlockBlock;
import net.mcreator.diabolica.block.HummusCanBlock;
import net.mcreator.diabolica.block.FluorescentLightZBlock;
import net.mcreator.diabolica.block.FluorescentLightYBlock;
import net.mcreator.diabolica.block.FluorescentLightXBlock;
import net.mcreator.diabolica.block.FluorescentLightWBlock;
import net.mcreator.diabolica.block.FluorescentLightVBlock;
import net.mcreator.diabolica.block.FluorescentLightUBlock;
import net.mcreator.diabolica.block.FluorescentLightTBlock;
import net.mcreator.diabolica.block.FluorescentLightSBlock;
import net.mcreator.diabolica.block.FluorescentLightRBlock;
import net.mcreator.diabolica.block.FluorescentLightQuestionBlock;
import net.mcreator.diabolica.block.FluorescentLightQBlock;
import net.mcreator.diabolica.block.FluorescentLightPeriodBlock;
import net.mcreator.diabolica.block.FluorescentLightPBlock;
import net.mcreator.diabolica.block.FluorescentLightOBlock;
import net.mcreator.diabolica.block.FluorescentLightNBlock;
import net.mcreator.diabolica.block.FluorescentLightMBlock;
import net.mcreator.diabolica.block.FluorescentLightLBlock;
import net.mcreator.diabolica.block.FluorescentLightKBlock;
import net.mcreator.diabolica.block.FluorescentLightJBlock;
import net.mcreator.diabolica.block.FluorescentLightIBlock;
import net.mcreator.diabolica.block.FluorescentLightHBlock;
import net.mcreator.diabolica.block.FluorescentLightGBlock;
import net.mcreator.diabolica.block.FluorescentLightFBlock;
import net.mcreator.diabolica.block.FluorescentLightExclamationBlock;
import net.mcreator.diabolica.block.FluorescentLightEBlock;
import net.mcreator.diabolica.block.FluorescentLightDashBlock;
import net.mcreator.diabolica.block.FluorescentLightDBlock;
import net.mcreator.diabolica.block.FluorescentLightCommaBlock;
import net.mcreator.diabolica.block.FluorescentLightCBlock;
import net.mcreator.diabolica.block.FluorescentLightBlock;
import net.mcreator.diabolica.block.FluorescentLightBBlock;
import net.mcreator.diabolica.block.FluorescentLightABlock;
import net.mcreator.diabolica.block.FluorescentLight9Block;
import net.mcreator.diabolica.block.FluorescentLight8Block;
import net.mcreator.diabolica.block.FluorescentLight7Block;
import net.mcreator.diabolica.block.FluorescentLight6Block;
import net.mcreator.diabolica.block.FluorescentLight5Block;
import net.mcreator.diabolica.block.FluorescentLight4Block;
import net.mcreator.diabolica.block.FluorescentLight3Block;
import net.mcreator.diabolica.block.FluorescentLight2Block;
import net.mcreator.diabolica.block.FluorescentLight1Block;
import net.mcreator.diabolica.block.FluorescentLight0Block;
import net.mcreator.diabolica.block.EnhcancedCraftingTableBlock;
import net.mcreator.diabolica.block.DingyTilesBlock;
import net.mcreator.diabolica.DiabolicaMod;

public class DiabolicaModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, DiabolicaMod.MODID);
	public static final RegistryObject<Block> LIMBO_BLOCK = REGISTRY.register("limbo_block", () -> new LimboBlockBlock());
	public static final RegistryObject<Block> DIABOLISM_TABLE = REGISTRY.register("diabolism_table", () -> new EnhcancedCraftingTableBlock());
	public static final RegistryObject<Block> LIMINAL_ROAD = REGISTRY.register("liminal_road", () -> new LiminalRoadBlock());
	public static final RegistryObject<Block> STRIPED_LIMINAL_ROAD = REGISTRY.register("striped_liminal_road", () -> new StripedLiminalRoadBlock());
	public static final RegistryObject<Block> ROAD_PLACER = REGISTRY.register("road_placer", () -> new RoadPlacerBlock());
	public static final RegistryObject<Block> ROAD_PLACER_2 = REGISTRY.register("road_placer_2", () -> new RoadPlacer2Block());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT = REGISTRY.register("fluorescent_light", () -> new FluorescentLightBlock());
	public static final RegistryObject<Block> PLASTER = REGISTRY.register("plaster", () -> new PlasterBlock());
	public static final RegistryObject<Block> DINGY_TILES = REGISTRY.register("dingy_tiles", () -> new DingyTilesBlock());
	public static final RegistryObject<Block> TILES = REGISTRY.register("tiles", () -> new TilesBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_A = REGISTRY.register("fluorescent_light_a", () -> new FluorescentLightABlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_B = REGISTRY.register("fluorescent_light_b", () -> new FluorescentLightBBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_C = REGISTRY.register("fluorescent_light_c", () -> new FluorescentLightCBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_D = REGISTRY.register("fluorescent_light_d", () -> new FluorescentLightDBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_E = REGISTRY.register("fluorescent_light_e", () -> new FluorescentLightEBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_F = REGISTRY.register("fluorescent_light_f", () -> new FluorescentLightFBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_G = REGISTRY.register("fluorescent_light_g", () -> new FluorescentLightGBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_H = REGISTRY.register("fluorescent_light_h", () -> new FluorescentLightHBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_I = REGISTRY.register("fluorescent_light_i", () -> new FluorescentLightIBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_J = REGISTRY.register("fluorescent_light_j", () -> new FluorescentLightJBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_K = REGISTRY.register("fluorescent_light_k", () -> new FluorescentLightKBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_L = REGISTRY.register("fluorescent_light_l", () -> new FluorescentLightLBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_M = REGISTRY.register("fluorescent_light_m", () -> new FluorescentLightMBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_N = REGISTRY.register("fluorescent_light_n", () -> new FluorescentLightNBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_O = REGISTRY.register("fluorescent_light_o", () -> new FluorescentLightOBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_P = REGISTRY.register("fluorescent_light_p", () -> new FluorescentLightPBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_Q = REGISTRY.register("fluorescent_light_q", () -> new FluorescentLightQBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_R = REGISTRY.register("fluorescent_light_r", () -> new FluorescentLightRBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_S = REGISTRY.register("fluorescent_light_s", () -> new FluorescentLightSBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_T = REGISTRY.register("fluorescent_light_t", () -> new FluorescentLightTBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_U = REGISTRY.register("fluorescent_light_u", () -> new FluorescentLightUBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_V = REGISTRY.register("fluorescent_light_v", () -> new FluorescentLightVBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_W = REGISTRY.register("fluorescent_light_w", () -> new FluorescentLightWBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_X = REGISTRY.register("fluorescent_light_x", () -> new FluorescentLightXBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_Y = REGISTRY.register("fluorescent_light_y", () -> new FluorescentLightYBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_Z = REGISTRY.register("fluorescent_light_z", () -> new FluorescentLightZBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_0 = REGISTRY.register("fluorescent_light_0", () -> new FluorescentLight0Block());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_1 = REGISTRY.register("fluorescent_light_1", () -> new FluorescentLight1Block());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_2 = REGISTRY.register("fluorescent_light_2", () -> new FluorescentLight2Block());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_3 = REGISTRY.register("fluorescent_light_3", () -> new FluorescentLight3Block());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_4 = REGISTRY.register("fluorescent_light_4", () -> new FluorescentLight4Block());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_5 = REGISTRY.register("fluorescent_light_5", () -> new FluorescentLight5Block());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_6 = REGISTRY.register("fluorescent_light_6", () -> new FluorescentLight6Block());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_7 = REGISTRY.register("fluorescent_light_7", () -> new FluorescentLight7Block());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_8 = REGISTRY.register("fluorescent_light_8", () -> new FluorescentLight8Block());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_9 = REGISTRY.register("fluorescent_light_9", () -> new FluorescentLight9Block());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_PERIOD = REGISTRY.register("fluorescent_light_period", () -> new FluorescentLightPeriodBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_COMMA = REGISTRY.register("fluorescent_light_comma", () -> new FluorescentLightCommaBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_DASH = REGISTRY.register("fluorescent_light_dash", () -> new FluorescentLightDashBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_EXCLAMATION = REGISTRY.register("fluorescent_light_exclamation", () -> new FluorescentLightExclamationBlock());
	public static final RegistryObject<Block> FLUORESCENT_LIGHT_QUESTION = REGISTRY.register("fluorescent_light_question", () -> new FluorescentLightQuestionBlock());
	public static final RegistryObject<Block> HUMMUS_CAN = REGISTRY.register("hummus_can", () -> new HummusCanBlock());
}
